server:
  port: 7001

spring:
  application:
    name: EUREKA-SERVER
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Eureka配置
eureka:
  instance:
    instance-id: EUREKA-SERVER-7001
    hostname: localhost # Eureka服务端的名字
  client:
    register-with-eureka: true # 表示是否想Eureka中心注册自己
    fetch-registry: false # fetch-registry如果为false，则表示自己为注册中心
    service-url:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/